#!/bin/bash

# 🎯 Manual Deployment Guide for Render.com
# Step-by-step instructions for deploying Oref Alerts API

echo "🎯 Oref Alerts API - Manual Deployment Guide"
echo "============================================"
echo ""
echo "📋 Prerequisites:"
echo "   ✅ GitHub repository: https://github.com/nadavsimba24/oref-alerts-api"
echo "   ✅ Render.com account"
echo "   ✅ 5 minutes of time"
echo ""
echo "🚀 Step-by-Step Deployment:"
echo ""
echo "1. 📱 OPEN RENDER DASHBOARD"
echo "   👉 https://dashboard.render.com/new/web"
echo ""
echo "2. 🔗 CONNECT GITHUB"
echo "   • Click 'Connect a GitHub repository'"
echo "   • Authorize Render to access your GitHub"
echo "   • Search for: 'nadavsimba24/oref-alerts-api'"
echo "   • Click 'Connect'"
echo ""
echo "3. ⚙️ AUTO-CONFIGURATION (from render.yaml)"
echo "   • Render will automatically detect:"
echo "     - Build Command: 'npm install && npm run build'"
echo "     - Start Command: 'npm start'"
echo "     - Health Check Path: '/health'"
echo "     - Environment Variables: NODE_ENV, PORT, etc."
echo "   • Service Name: 'oref-alerts-api' (auto-filled)"
echo ""
echo "4. 🎯 CREATE SERVICE"
echo "   • Click the blue 'Create Web Service' button"
echo "   • Wait 2-3 minutes for deployment"
echo ""
echo "5. ⏳ DEPLOYMENT PROGRESS"
echo "   • Watch the real-time logs"
echo "   • You'll see:"
echo "     - Cloning repository"
echo "     - Installing dependencies"
echo "     - Building TypeScript"
echo "     - Starting server"
echo "     - Health check passing"
echo ""
echo "6. ✅ DEPLOYMENT COMPLETE"
echo "   • You'll get a URL like:"
echo "     https://oref-alerts-api.onrender.com"
echo ""
echo "🔧 Testing Your Deployment:"
echo ""
echo "After deployment, open these URLs in your browser:"
echo ""
echo "1. Health Check:"
echo "   👉 https://oref-alerts-api.onrender.com/health"
echo "   Expected: {\"status\":\"ok\",\"timestamp\":\"...\"}"
echo ""
echo "2. Current Alerts:"
echo "   👉 https://oref-alerts-api.onrender.com/api/alerts/current"
echo "   Expected: JSON with current alerts"
echo ""
echo "3. WebSocket Test (use developer tools):"
echo "   Connect to: ws://oref-alerts-api.onrender.com"
echo ""
echo "📊 Monitoring:"
echo ""
echo "• Logs: https://dashboard.render.com → Services → oref-alerts-api → Logs"
echo "• Metrics: https://dashboard.render.com → Services → oref-alerts-api → Metrics"
echo "• Settings: https://dashboard.render.com → Services → oref-alerts-api → Settings"
echo ""
echo "⚡ Quick Test Script (run after deployment):"
cat << 'EOF'

# After deployment, run this to test:
echo "Testing Oref Alerts API deployment..."
echo ""

# Test health endpoint
echo "1. Testing health endpoint:"
curl -s "https://oref-alerts-api.onrender.com/health" | jq -r '"Status: \(.status), Timestamp: \(.timestamp)"' 2>/dev/null || echo "Health check failed"

# Test alerts endpoint
echo ""
echo "2. Testing current alerts:"
curl -s "https://oref-alerts-api.onrender.com/api/alerts/current" | jq -r '"Alert: \(.alert), Cities: \(.current.data | join(", "))"' 2>/dev/null || echo "Alerts endpoint failed"

echo ""
echo "✅ Deployment test complete!"
EOF

echo ""
echo "📁 Project Files Summary:"
echo ""
echo "• render.yaml - Auto-configuration for Render"
echo "• Dockerfile - Docker container configuration"
echo "• src/ - TypeScript source code"
echo "• package.json - Dependencies and scripts"
echo "• *.md - Comprehensive documentation"
echo ""
echo "🎉 Ready to deploy! Open the dashboard and start:"
echo "   https://dashboard.render.com/new/web"
echo ""
echo "⏰ Estimated time: 5 minutes"
echo "💰 Cost: Free (Starter plan)"
echo "🌐 Result: Public HTTPS API with WebSocket support"